M48
; DRILL file {KiCad (6.0.6)} date Thu Sep 22 18:41:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-22T18:41:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.7441Y-2.5787
X4.7441Y-4.8228
X6.122Y-2.8543
X6.437Y-4.8228
T0
M30
